### ISSUE TITLE
Support tower-sessions

### ISSUE THREAD

**Issue by Markusdreyer** [maxcountryman/axum-login#101]
With the [`axum-sessions`](https://github.com/maxcountryman/axum-sessions) crate migrating to [`tower-sessions`](https://github.com/maxcountryman/tower-sessions), are there any plans to update this crate to use [`tower-sessions`](https://github.com/maxcountryman/tower-sessions) instead?

**Comment by maxcountryman** [comment]
Yes. I've created a discussion about this [over here](https://github.com/maxcountryman/axum-login/discussions/100) and could use feedback.

**Comment by maxcountryman** [comment]
@Markusdreyer I've opened #104 if you'd like to take a look.

**Comment by maxcountryman** [comment]
We've released `v0.7.0` which leverages `tower-sessions`.
