### ISSUE TITLE
Idea: RBAC support 

### ISSUE THREAD

**Issue by Czocher** [maxcountryman/axum-login#11]
As mentioned in #8 either an example or additional support traits or methods for RBAC would benefit the project.

@maxcountryman do you have some ideas on how this would look like? 

What I imagine is a `get_role() -> Option<R>` method on `AuthUser` where `R` is some `enum` defining the possible roles for a user.

Additionally some (generic?) extractor (or maybe a macro to generate such an extractor) to allow only users with at least one of the roles specified in the extractor parameters, would be perfect.

This can possibly be implemented in a backwards-compatible way by providing a default implementation for the new method, which would return `None`.

**Comment by maxcountryman** [comment]
That makes sense to me. I'm not sure if there are more complete (and generic) implementations of RBAC already in the Rust ecosystem. But barring that, an enum like you describe seems like a good direction.
