### ISSUE TITLE
Error type made public

### ISSUE THREAD

**Issue by BurntNail** [maxcountryman/axum-login#119]
Hi,

For some reason the `session::Error` type is public, but not re-exported anywhere so I can't match on it to get my backend error out. Is there any chance this could be changed to be re-exported for 0.7.4?

**Comment by maxcountryman** [comment]
Sorry about that. Absolutely! It's intended to be accessible, so we'll address that in the next release.

**Comment by maxcountryman** [comment]
Just to clarify, `axum_login::tower_sessions::session::Error` isn't what you're looking for, right?

**Comment by maxcountryman** [comment]
This will be part of the 0.8.0 release which I'll cut presently.

**Comment by maxcountryman** [comment]
0.8.0 is now released.

**Comment by BurntNail** [comment]
That's got to be the fastest issue resolution I've ever been a part of - thanks!
