### ISSUE TITLE
Implement a role-based `RequireAuthorizationLayer`

### ISSUE THREAD

**Issue by Czocher** [maxcountryman/axum-login#14]
The layer should not only check the login and password, but also if the user has the right role.

@maxcountryman I understand that your idea is a `RequireAuthorizarionLayer` separate from the normal `login` one - the difference being it would also check the role of the user?

**Comment by maxcountryman** [comment]
That's right.

I wonder if we could extend `RequireAuthorizationLayer` such that it provides a `role` or similar method?

I haven't thought about this too deeply, but it seems it would have to match a particular variant of the enum (or perhaps some set of variants). This is a bit tricky because I think it'll require some way of calling back to the provided implementation in order to understand which role variants are allowed and which aren't.

**Comment by maxcountryman** [comment]
Maybe this could look something like:

```rust
fn has_admin<Role>(user_role: Role) -> bool {
    user_role == MyRole::Admin
}

let authz_layer = RequireAuthorizationLayer::role(has_admin);
```

Then the `authorization` implementation would call the provided predicate against the actual `Role` the logged in user has.

Importantly, `has_admin` is arbitrary and user-defined. So our users can provide any implementation of `Role` that suits their needs and decide what the logic for accepting a valid role for a given user is within the scope of the provided function.

**Comment by Czocher** [comment]
This would work well, but I also wonder if we can do it in some other way, more closely related to the `handler` params. As a potential user of this kind of functionality I'd really like to define which roles (or some kind of role-based predicate) to allow when defining handler parameters, similar to how we define `Extensions` in `axum` or `Guards` in `rocket.rs`. Something like:

```rust
fn some_handler(RequireRole(admin): RequireRole<Admin>) {
    ...
}
```

Unfortunately `enum` variants are not types, so it kinda complicates the matter, but there's a "workaround":

```rust
struct Admin;
struct User;

enum Roles {
    User(User)
    Admin(Admin)
}
```
then the `User` and `Admin` structs can be used as generic types. I'm not yet sure if we can match on them in a reasonable way though or how they'd get mapped by `sqlx`.

What are your thoughts @maxcountryman?

**Comment by Czocher** [comment]
I asked about ideas from axum devs and here's the discussion: https://github.com/tokio-rs/axum/discussions/1533

**Comment by maxcountryman** [comment]
> I'd really like to define which roles (or some kind of role-based predicate) to allow when defining handler parameters

I'm curious about this: is the goal to make it easier to extract the user or something else?

> Another idea I had is creating a simple function which can be used as a middleware for a single handler or as a layer (or route_layer).

What's the advantage of this over using `RequireAuthorizationLayer` and wrapping `custom` like we do with `login`?

One thing to bear in mind here is that there's nothing stopping our users from implementing their own extractors and layers and so ideally what we provide in the library fits well with what's already provided out of the box.

**Comment by Czocher** [comment]
> I'm curious about this: is the goal to make it easier to extract the user or something else?

Easier to extract the user with the right role or return the authorization error early.

> What's the advantage of this over using `RequireAuthorizationLayer` and wrapping `custom` like we do with `login`?

I analysed the implementation of `RequireAuthorizationLayer` and you're right, there's not much benefits except maybe being slightly more user-friendly (but that's debatable ;)). I'll implement the solution based on the `RequireAuthorizationLayer`.
