### ISSUE TITLE
login_required macro generates invalid redirect URL

### ISSUE THREAD

**Issue by benwilber** [maxcountryman/axum-login#143]
https://github.com/maxcountryman/axum-login/blob/8ed2bbc8bbb945a6aa9c62983f99eb7f80765b6c/axum-login/src/middleware.rs#L141

If my login_url already has a querystring then this will append a new query string with a new `?` which will produce an invalid URL

**Comment by maxcountryman** [comment]
Happy to accept a PR that provides better handling of this.

**Comment by benwilber** [comment]
Unless you're willing to depend on a url parsing library, I don't think this macro should try to add a `next` parameter at all.  I know that Django does that but it's only because a url parser is available in the stdlib.
