### ISSUE TITLE
Additional unit tests?

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/axum-login#15]
Currently there's a solitary test which shows that the library functions at some basic level. It would be nice to extend test coverage to ensure other parts of the library behave as we'd like. For example, testing the new role functionality might be good and no doubt there are other places we could introduce testing to help increase confidence in the code.

**Comment by Czocher** [comment]
Can we generate the test coverage as a project badge to see what potential areas are there to test?

**Comment by maxcountryman** [comment]
We can. I haven't set this up in a while so I don't recall the specific tools we need. We could look at how sqlparser does it, as an example. If you're so inclined, it'd be helpful to set that up as a first step.

**Comment by czotomo** [comment]
FWIW here's `tarpaulin` report for `main` branch:
```
Dec 11 00:18:55.877  INFO cargo_tarpaulin::report: Coverage Results:
|| Uncovered Lines:
|| src/auth.rs: 107, 109, 122-127, 129, 145-147, 149, 164, 166, 185, 190-193, 195, 198-201, 204, 226-229, 242-245
|| src/auth_user.rs: 70-71
|| src/extractors.rs: 71, 82, 114-116, 130-133, 136
|| src/lib.rs: 169, 189
|| src/memory_store.rs: 41
|| src/sqlx_store.rs: 32, 35-37, 43-46
|| Tested/Total Lines:
|| src/auth.rs: 20/54
|| src/auth_user.rs: 0/2
|| src/extractors.rs: 24/34
|| src/lib.rs: 0/2
|| src/memory_store.rs: 4/5
|| src/sqlx_store.rs: 0/8
||
45.71% coverage, 48/105 lines covered
```

**Comment by czotomo** [comment]
@maxcountryman 
would you consider adding [Codecov](https://about.codecov.io/pricing/) integration?
Apparently it's free for Open Source projects with public repos so it might be an easy way to add reports and thresholds for coverage for new PRs

**Comment by maxcountryman** [comment]
@czotomo does coveralls not fit your needs?

**Comment by czotomo** [comment]
Oh wow, I didn't even realize it's set-up already. Apologies for this useless noise.

**Comment by maxcountryman** [comment]
I'll close this for now. We can continue to add to the test suite as it merits value.
