### ISSUE TITLE
Tower Sessions dependency breaks compability

### ISSUE THREAD

**Issue by mdegel** [maxcountryman/axum-login#189]
## Bug Report
Compiling a previously stable code base is now failing with the following error:
```powershell
   Compiling axum-login v0.13.1
error[E0106]: missing lifetime specifier
   --> C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\axum-login-0.13.1\src\service.rs:128:48
    |
128 |     type Service = CookieManager<SessionManager<AuthManager<S, Backend>, Sessions>>;
    |                                                ^ expected named lifetime parameter
    |
help: consider introducing a named lifetime parameter
    |
128 |     type Service<'a> = CookieManager<SessionManager<'a, AuthManager<S, Backend>, Sessions>>;
    |                 ++++                                +++

For more information about this error, try `rustc --explain E0106`.
error: could not compile `axum-login` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

### Version
0.13.1

### Platform
64-bit (Windows)

### Crates
tower-sessions v0.10.3
tower-sessions-core v0.10.3
tower-sessions-memory-store v0.10.3

### Description
The issue appears to be caused by the implicit update of tower-sessions v0.10.2  -> v0.10.3.
See: https://github.com/maxcountryman/tower-sessions/pull/158
Specifically: https://github.com/maxcountryman/tower-sessions/pull/158/files#diff-5c6f87176b7f64fbbeabbc31f5ad377edc268ebeb231eb55ee31c14ec3834f23R69

Downgrading to tower-sessions v0.10.2 allows successfully building again:
```
tower-sessions = "=0.10.2"
```

**Comment by maxcountryman** [comment]
It's unfortunate that the semver guide does not list lifetimes as breaking or at all seemingly. However, they aren't implied in the definition of the associated type so unfortunately this does seem broken.

We can either republish as 0.11.0 or author 0.10.4 with the static lifetime hardcoded on config, yanking 0.10.3 in either case.

I'll be able to get to this later on this morning.

**Comment by maxcountryman** [comment]
The release is yanked so that closes this ticket.

As I mentioned, we'll author new changes with tower-sessions without breaking semver shortly.
