### ISSUE TITLE
Redirect unauthenticated user to login page.

### ISSUE THREAD

**Issue by cldershem** [maxcountryman/axum-login#22]
I have been hoping to replace my custom/fragile middleware I built around `axum-sessions` with `axum-login`. One of the things I cannot figure out with this library is how to redirect an unauthenticated user to the login page.

- user tries to go to "example.com/requires_auth"
- user is redirected to "example.com/login?next_url=/requires_auth"
- user logs in
- user is redirected back to "example.com/requries_auth"

Right now, because of how "requries_auth" attempts to extract a user, there is no way to redirect when there is no user available.

Do you have a recommendation or am I going about this all wrong?

**Comment by maxcountryman** [comment]
Thanks for raising this: one thought here is we may want to extend the way auth requirement works to support this. However in the meantime, applications can define their own methods for this as well. (That said, I do think it would be great to incorporate this into the crate directly.)

**Comment by cldershem** [comment]
I would gladly work on adding this feature if you could give me a little guidance. I had this feature working in my rudimentary custom middleware I was using before I swapped it out for `axum-login`, but I'm a bit lost as to where this would best fit in this codebase.

**Comment by maxcountryman** [comment]
I put together [a quick example](https://github.com/maxcountryman/axum-login/blob/32400284b5a825bbc110f4256b8ce1b0fb51df55/examples/redirect/src/main.rs#L76-L95) of how you might do this currently.

Let me know if this would fit your use case.

**Comment by apps4uco** [comment]
I have another suggestion that works for my use case, Im not sure about the OP s use case.
It seems like a pretty standard thing to do but I havent found an existing middleware to do this.
Comments welcome.

```
.route("/protected", get(protected_handler))
.route_layer(RequireAuthorizationLayer::<User>::login())
//other routes
.layer(
            ServiceBuilder::new()
                .layer(session_layer)
                .layer(auth_layer)
                .map_response(|r: Response|{
                    if r.status()==StatusCode::UNAUTHORIZED {
                        Redirect::to("/login").into_response()
                    } else {
                        r
                    }
                })
        )
```

**Comment by zmlgit** [comment]
> I put together [a quick example](https://github.com/maxcountryman/axum-login/blob/32400284b5a825bbc110f4256b8ce1b0fb51df55/examples/redirect/src/main.rs#L76-L95) of how you might do this currently.
> 
> Let me know if this would fit your use case.
I have a similar problem。
In oauth2 flow, User attempt access `http://localhost:9001/authorize?response_type=code&scope=foo&client_id=oauth-client-1&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fcallback&state=Lwt50DDQKUB8U7jtfLQCVGDL9cnm` 

But the user hasn't logged in yet，the flow step could be:

1, redirect to login page;
2, after login success, redirect to /authorize, carries all parameters

How can I deal this case?

In another case. I want to give a custom response, Can supply a function as an input parameter of the layer?

**Comment by maxcountryman** [comment]
Did you look at the example? That case is covered by redirecting when no user is found.

**Comment by zmlgit** [comment]
I've looked at this example，It requires the user to carry the parameters of the redirect，and access login page，What I'm asking is the intercept redirect to login page

**Comment by maxcountryman** [comment]
You can do that using the same technique in the example. You'll check for a current user and decide how you want proceed accordingly in your handler.

**Comment by zmlgit** [comment]
1,user access
`http://localhost:9001/authorize?response_type=code&scope=foo&client_id=oauth-client-1&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fcallback&state=Lwt50DDQKUB8U7jtfLQCVGDL9cnm`,
2, no user found, server give a 302 code,redirect to login,**(in this step, how to carry the parameters)**
3, login and to the right url

**Comment by maxcountryman** [comment]
Please look at the example. It shows you how to store parameters which will address the use case you're describing. The idea is to use the session to capture state like this. You can adapt this technique to work for anonymous and logged in users.

**Comment by zmlgit** [comment]
use session seems a good idea, thank you very much

**Comment by maxcountryman** [comment]
I would also consider simply using the query string directly, as the example illustrates. You don't need to store state outside of the URL in many cases, such as the one you're describing. As an alternative you can persist state in the session. However I'd consider why you need to do that when you can simply attach a query string to each redirect.
