### ISSUE TITLE
Session is loaded even if handler doesn't need it

### ISSUE THREAD

**Issue by arcstur** [maxcountryman/axum-login#221]
- [x] I have looked for existing issues (including closed) about this

### Version

0.15.1

### Platform

Linux 6.8.8-arch1-1

### Description

The Auth layer loads a session even if it's not needed. I modified the sqlite example and added a new empty route

```
.route(
    "/anything",
    axum::routing::get(|| async { "hello".to_owned() }),
)
```

When accessing this route, the underlying SessionStore `load` method gets called, but the route doesn't need authentication.

When using just `tower-sessions` instead of `axum-login`, it doesn't happen.

**Comment by maxcountryman** [comment]
It's because of the messages middleware.

If it's important to you, the messages middleware can be extended to remove itself from the session when it's entirely empty.

**Comment by arcstur** [comment]
Even removing the messages middleware and removing the axum_messages dependency it still does this.

**Comment by maxcountryman** [comment]
Then your session isn't empty and this is expected behavior.

**Comment by arcstur** [comment]
But why is the session loaded on a route that doesn't need it? This is axum-login behavior and not tower-sessions behavior.

**Comment by maxcountryman** [comment]
See above; this crate uses tower-sessions.

Please use the Discussions forum to ask questions so we can partition bug reports from support and general Q&A.
