### ISSUE TITLE
On Windows there is no icon

### ISSUE THREAD

**Issue by frederikhors** [maxcountryman/axum-login#242]
On Windows there is no icon:

![image](https://github.com/user-attachments/assets/9aec15bf-7aa6-40c3-a3bc-6304ed066d80)

and

![image](https://github.com/user-attachments/assets/f931ba24-ea24-499b-a2a5-6cdfb5374950)

**Comment by frederikhors** [comment]
And

![image](https://github.com/user-attachments/assets/0b09ec14-e6d6-4f61-85d0-fbf6072259a2)

**Comment by maxcountryman** [comment]
I don't use Windows too often, but this probably relates to the specific release of Windows (along with service packs, etc). For instance, I have Windows 11 installed on a computer and when I last checked the emoji were rendering as expected.

**Comment by frederikhors** [comment]
I'm on Win 10 right now.

**Comment by maxcountryman** [comment]
Not too much that can be done from this side. Maybe there's an update for Windows 10 that includes the missing emojis?

**Comment by frederikhors** [comment]
What about changing these 2 icons?

**Comment by maxcountryman** [comment]
I'm not interested in changing the emoji.
