### ISSUE TITLE
sqlx_store::SqlxStore is a private module

### ISSUE THREAD

**Issue by beckend** [maxcountryman/axum-login#25]
Trying to return `sqlx_store::SqlxStore` in a init function to bootstrap application.

**Comment by beckend** [comment]
Precisely `sqlx_store::SqlxStore`

**Comment by maxcountryman** [comment]
We can make this public but note that it'll require generics or the concrete specification of those. The latter case is accounted for by pool type via the public types, e.g. `MssqlStore`, etc.

**Comment by beckend** [comment]
Of course
