### ISSUE TITLE
How to redirect with the auth headers/cookie?

### ISSUE THREAD

**Issue by Rigellute** [maxcountryman/axum-login#3]
Firstly, thank you for creating this library!

I'm implementing an OAuth flow where the provider redirects back to our server, we exchange the code for a token, login the user, then redirect to another internal route e.g.:

```rs
async fn oauth_callback(mut auth: AuthContext) -> impl IntoResponse {
     // I've omitted the oauth details such as code exchange for the token
     let user = find_user_somehow();

    // login the user
    auth.login(&user).await.unwrap();
    
    // This redirect causes the session to be lost, I think we need to pass along the headers that contain the cookie?
    Redirect::to("/")
}

// in main
let app = Router::new()
   .route("/auth/google/callback", get(oauth_callback))
```
Axum has an [example of the OAuth flow](https://github.com/tokio-rs/axum/blob/0.5.x/examples/oauth/src/main.rs#L196), which looks like this:
```rs
    // Create a new session filled with user data
    let mut session = Session::new();
    session.insert("user", &user).unwrap();

    // Store session and get corresponding cookie
    let cookie = store.store_session(session).await.unwrap().unwrap();

    // Build the cookie
    let cookie = format!("{}={}; SameSite=Lax; Path=/", COOKIE_NAME, cookie);

    // Set cookie
    let mut headers = HeaderMap::new();
    headers.insert(SET_COOKIE, cookie.parse().unwrap());

    // Redirect with headers
    (headers, Redirect::to("/"))
```
How can we redirect and preserve the session? Can we get the headers after the `auth.login(...)` call?

**Comment by Rigellute** [comment]
I will put together an example 👍. 

Perhaps I have misunderstood or am missing something, but I think the problems is that when the oauth provider redirects to our server and we log the user in, the redirect to `"/"` alone does not pass along the newly made cookie. 

The axum example is constructing the cookie and explicitly returning the headers + redirect, which does work.

In my example above, removing the redirect preserves the session (leaving the user on the oauth callback route e.g. `/auth/google/callback`)

**Comment by maxcountryman** [comment]
I'm not clear on why the session would need to be set again.

Under the covers, we're using `axum-sessions` to maintain a cookie-based session, which should already exist on the client. The only way this wouldn't be true is if the client had never visited your site before entering this flow or if for example the session layer is missing from routes that handle that process.

The client itself basically only holds a pointer to the session the server is maintaining. (`async-session` does also support one format that's entirely embedded in the URL but this is not recommended.)

When calling `auth.login` we're updating the state of the session maintained by the server and so as long as the client still has its valid cookie we shouldn't need to set the cookie again.

For instance, with the default configuration, visiting any route which is wrapped with the session layer will set a cookie `axum.sid` on the client. Subsequent requests from the client should send that cookie. Meanwhile the server will update the session to ensure e.g. logged in state is set appropriately.

At any rate, an example would definitely be helpful. 🙂

**Comment by Rigellute** [comment]
Here is the oauth flow example: https://github.com/maxcountryman/axum-login/pull/4.

It demonstrates the problem I am facing: after the successful oauth callback, code/token exchange and `auth.login(...)`, redirecting to the `/protected` route is returning 401.

**Comment by maxcountryman** [comment]
I think this is resolved now.
