### ISSUE TITLE
Support `Sled` key-value store as a `Store`

### ISSUE THREAD

**Issue by Czocher** [maxcountryman/axum-login#34]
I recently came across [Sled](https://sled.rs/) when I searched for other possibilities for persistent application state. I think it would be nice to support it as an alternative for `sqlx`.

**Comment by maxcountryman** [comment]
Agree this looks cool! Just skimming the project, it looks like they have some kind of async story so that bodes well.

I'm open to adding this.

**Comment by Czocher** [comment]
I [asked](https://github.com/spacejam/sled/issues/1436)  the authors about any special handling we need to perform.

**Comment by Czocher** [comment]
Hello,
I had a discussion on the `sled` Discord and it seems that this project should be considered dead and replaced by [marble](https://github.com/komora-io/marble). I'll close this issue since there's no reason to implement support for an abandoned project. We can check if we can implement `marble` support in another task.
