### ISSUE TITLE
Support `rustqlite` as an alternative `Store`

### ISSUE THREAD

**Issue by czocher** [maxcountryman/axum-login#35]
[Rustqlite](https://github.com/rusqlite/rusqlite) seems like a good alternative for the `sqlx` sqlite one since it supports `sqlite` on a far better level. I believe it would be beneficial to support it separately.

**Comment by maxcountryman** [comment]
It looks neat but correct me if I'm wrong: it doesn't support async currently, right?

**Comment by Czocher** [comment]
@maxcountryman you're correct, it does not support async and is not multithread-safe. In reality `sqlite` is never `async` nor `multithread-safe`. AFAIK it needs to be kept behind a `Mutex`. `Sqlx` and other async database access libraries either do that or employ some kind of message passing approach.

I was thinking on using [tokio-rusqlite](https://docs.rs/tokio-rusqlite/0.3.0/tokio_rusqlite/) to overcome this problem.

**Comment by rgwood** [comment]
I tried to use `axum-login` in a project that uses `rusqlite` today. Initially it seemed pretty straightforward, but implementing`UserStore` was harder than expected:

```
#[derive(Clone, Debug, PartialEq)]
pub struct UserRepository {
    conn: ConnectionPool,
}

impl UserStore<i64, Role> for UserRepository {
    // nearly everything in this impl was generated by the "Implement missing members" Quick Fix in rust-analyzer
    #[doc = " An associated user type which will be loaded from the store."]
    type User = User;

    #[doc = " Load and return a user."]
    #[doc = ""]
    #[doc = " This provides a generic interface for loading a user from some store."]
    #[doc = " For example, this might be a database or cache. It\'s assumed that a"]
    #[doc = " unique, stable identifier of the user is available. See [`AuthUser`]"]
    #[doc = " for expected minimal interface of the user type itself."]
    #[must_use]
    #[must_use]
    #[allow(clippy::type_complexity,clippy::type_repetition_in_bounds)]
    fn load_user<'life0,'life1,'async_trait>(&'life0 self,user_id: &'life1 i64) ->  ::core::pin::Pin<Box<dyn ::core::future::Future<Output = Result<Option<Self::User> > > + ::core::marker::Send+'async_trait> >where 'life0:'async_trait,'life1:'async_trait,Self:'async_trait {
        todo!()
    }
}
```

The lifetimes are impenetrable and it seems like `load_user` needs to return a `Result<T, E>` where `E` is [an error type from a library I've never used before](https://docs.rs/eyre/0.6.8/eyre/struct.Report.html). I gave up after 5-10 minutes of digging into that.

(apologies, I know I should have kept trying to figure this out)

**Comment by czocher** [comment]
This is an `async_trait` @rgwood. You should implement it as described in the example of: https://crates.io/crates/async-trait.

**Comment by czocher** [comment]
@rgwood if you provide a work-in-progress PR I can have a look and maybe help you with the details.

**Comment by rgwood** [comment]
Thank you for the help and offer! I ended up implementing it like this:

```rust
#[derive(Clone)]
pub struct SqliteUserStore {}

// uggggggh async is the worst
#[async_trait]
impl UserStore<i64, Role> for SqliteUserStore {
    type User = User;

    async fn load_user(
        &self,
        user_id: &i64,
    ) -> std::result::Result<Option<Self::User>, eyre::Report> {
        let conn = get_conn_from_pool()
            .map_err(|e| eyre::eyre!("could not get db connection: {}", e))?;
        let user = get_user(&conn, *user_id)
            .map_err(|e| eyre::eyre!("could not get user: {}", e))?;
        Ok(user)
    } 
}
```

I figure that reading from my small local SQLite DB is fast enough that a blocking read is OK here. 🤞

**Comment by czocher** [comment]
@maxcountryman @rgwood I'll try to provide a PR with an async version as soon as I overcome some dependency related issues.

The current problems I'm facing:
- The `UserId` parameter is provided as a reference which needs to be shared between threads. Not sure how to do it yet.
- `rusqlite` conflicts with `sqlx`, since they both link to the C sqlite library. Both features are not additive, which is a problem overall, but I don't think we can do anything about it. 

Any help/ideas are welcomed.

**Comment by czocher** [comment]
@rgwood the implementation is finalized, you can probably copy the solution for an `async` version if you'd like.

**Comment by maxcountryman** [comment]
I believe we can close this now that we no longer bundle user stores.
