### ISSUE TITLE
Support Sea-ORM as a store

### ISSUE THREAD

**Issue by limjiayi** [maxcountryman/axum-login#36]
[Sea-ORM](https://github.com/SeaQL/sea-orm) is a popular async ORM that uses `sqlx` under the hood. There is a [discussion](https://github.com/maxcountryman/axum-login/discussions/28) about creating a store for it, but it would be awesome if `axum-login` supports this out of the box.

**Comment by maxcountryman** [comment]
I'd be happy to support it directly.

**Comment by limjiayi** [comment]
> I'd be happy to support it directly.

This would be fantastic, I'd use it the moment it lands!

**Comment by konrad-grochowski** [comment]
I'm interested in taking this up. Doing experiments currently.

**Comment by maxcountryman** [comment]
We no longer bundle user stores/backends.
