### ISSUE TITLE
Calling AuthContext::login does not compare password hashes until next request

### ISSUE THREAD

**Issue by CaptainMaso** [maxcountryman/axum-login#46]
Calling the AuthContext::login function doesn't seem to be checking whether the supplied user has the correct password. 
This is fine in lots of cases since the next request checks the password hash, sees that they don't match and logs the user out. I found this slightly misleading, as I then tried to use the `current_user` field assuming that the password hashes had been validated.

I think the current behaviour is fine, but it might be worth documenting somewhere pretty obviously that the AuthContext::login function does not actually validate that the supplied user details are correct and just adds them to the user's session and `current_user` field, and that validating the supplied user is left up to the developer.

**Comment by maxcountryman** [comment]
> Calling the AuthContext::login function doesn't seem to be checking whether the supplied user has the correct password.

Correct. `axum-login` is completely agnostic to this. That's very much by design. We don't want to impose constraints on the precise methods for authenticating.

If you'd like to extend the documentation, please feel free to do so. 🙂

**Comment by CaptainMaso** [comment]
Awesome, I thought that might be the case. Thanks!
