### ISSUE TITLE
New Session For Every Request

### ISSUE THREAD

**Issue by BeaconBrigade** [maxcountryman/axum-login#53]
I'm trying to implement a `/login` and `/logout` routes as well as some protected routes. However, after logging in, it seems like the log in isn't saved. When I ping `/login` it adds the user to a session, but by the time I try to access a protected route, the session and user are gone. I got the examples to work, but my repo based off of them just doesn't. Every protected route always returns forbidden and even the logout route says the `current_user` is `None`.

I inserted tracing everywhere to figure out what was happening and noticed that between each request a new session is created. I don't know if this is what's supposed to happen, but all of the data stored in the session is lost. 

My `SessionLayer` is built with a `MemoryStore` and my `AuthLayer` is built with an `SqliteStore`. I'm using `sqlx` and sqlite as a database. I made sure my users are stored in a table called `users` in my database.

If it helps, here's my setup  for the layers:

```rust
let session_store = MemoryStore::new();
let session_layer = SessionLayer::new(session_store, &config.session_secret);

let user_store =
    SqliteStore::<User, Role>::new(SqlitePool::connect(&config.database_file).await?);
let auth_layer = AuthLayer::new(user_store, &config.session_secret);
```

`config.session_secret` is a 64 byte array, and `config.database_file` is the path to my sqlite db. 

```rust
type RequireAuth = RequireAuthorizationLayer<User, Role>;

let app = Router::new()
    .route(
        "/lists",
        get(handlers::fetch_user_lists).layer(RequireAuth::login()),
    )
    .route(
        "/list",
        get(handlers::fetch_list).layer(RequireAuth::login()),
    )
    .route(
        "/get-lists",
        get(handlers::get_lists).layer(RequireAuth::login_with_role(Role::Admin..)),
    )
    .route(
        "/get-users",
        get(handlers::get_users).layer(RequireAuth::login_with_role(Role::Admin..)),
    )
    .route("/status", get(|| async { StatusCode::OK }))
    .route("/login", get(handlers::login))
    .route("/logout", get(handlers::logout))
    .layer(auth_layer)
    .layer(session_layer)
    .with_state(app_state);
```

The `app_state`  contains a sqlx pool for the database. The enum `Role`type looks like:

```rust
#[derive(
    Debug, Default, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Serialize, Deserialize, sqlx::Type,
)]
#[repr(i32)]
pub enum Role {
    /// Regular user access
    #[default]
    User = 0,
    /// Full access to the database
    Admin = 1,
}
```

I'm new to `axum-login`, so sorry for the information dump, I just wanted to put anything that might be useful. 

The `/login` route takes a json body which describes the user to log into, a name and password. The handler looks like this:

```rust
pub type AuthContext = axum_login::extractors::AuthContext<User, SqliteStore<User, Role>, Role>;

#[debug_handler]
pub async fn login(
    State(app): State<AppState>,
    mut auth: AuthContext,
    Json(user): Json<LoginUser>,
) -> AppResult<()> {
    debug!("logging in user: {user:?}");
    let user: User = sqlx::query_as("SELECT * FROM users WHERE name = ? AND password_hash = ?")
        .bind(&user.name)
        .bind(&user.password_hash)
        .fetch_one(&mut app.conn.acquire().await?)
        .await?;

    info!("user: {user:?}");

    auth.login(&user).await?;

    Ok(())
}
```

Inside the `/login` handler I can check `auth.current_user` and it is set correctly, but as soon as another route is called that is gone. For example on one run of the server:

Directly before calling `auth.login(&user).await?`

```rust
Session { 
    id: "jGomHmRqscfQGcLIpZPLzQvN8lDqlQ5qQJMA0GHlamQ=", 
    expiry: Some(2023-02-10T02:20:06.301437200Z), 
    data: RwLock { 
        data: {}, 
        poisoned: false, 
        .. 
    }, 
    cookie_value: Some("A/MJXP4FMV+rWiRmZMg0X5frpm9Gzt8dqSBCDW/YdVwroQTlmyocXT+X5FnMM5te4Y4PMnKmUwJT5kpBCXa+oQ=="), 
    data_changed: false, 
    destroy: false 
}
```

Directly after:

```rust
Session { 
    id: "jGomHmRqscfQGcLIpZPLzQvN8lDqlQ5qQJMA0GHlamQ=", 
    expiry: Some(2023-02-10T02:20:06.301437200Z), 
    data: RwLock { 
        data: {
            "_user_id": "\"3\"", 
            "_auth_id": "\"0qL/ZztGgEixRWFrMorDFNUsauceo4vmDcHcohY18PLWUUxTVc0/0SSSYMYeAaut45ZgEXbPJa1xeQBpyKP86w==\""
        }, 
        poisoned: false, 
        .. 
    }, 
    cookie_value: Some("A/MJXP4FMV+rWiRmZMg0X5frpm9Gzt8dqSBCDW/YdVwroQTlmyocXT+X5FnMM5te4Y4PMnKmUwJT5kpBCXa+oQ=="), 
    data_changed: true, 
    destroy: false 
}
```

You can see that the `user_id` has been added to the session. But, on the next request to `/lists` (or any route, it's all the same) we have:

```rust
Session { 
    id: "txK5yTK9y5Hyu6wxcSF6SwK079pmdSI7n/YV7RPg/HQ=", 
    expiry: Some(2023-02-10T02:20:13.404553800Z), 
    data: RwLock { 
        data: {}, 
        poisoned: false,
        ..
    }, 
    cookie_value: Some("29tPyCptmKMlBSJ8D08lYs1zFdz7NXaHouUiSt6u1o9JZvCI/OzmvZntzUSB6iMqFfI37YCkmKqZaKjQ8DsXjg=="), 
    data_changed: false, 
    destroy: false 
}
```

All of a sudden we have a brand new session with the old data gone. I've been struggling for hours trying to find out what I'm doing wrong, and at this point I'm pretty sure it's just some tiny thing I'm missing. Or of course, I'm just misunderstanding how I should be using the library. If so, _please_ let me know. I'd really appreciate if anyone could take a look and see if they notice anything out of order. Also, if you want more information just let me know. Thanks in advance

**Comment by maxcountryman** [comment]
Have you tried toggling secure? Note that the examples disable secure because they assume you'll be running locally. By default it's enabled.

**Comment by BeaconBrigade** [comment]
Yes. I tried `with_secure` on the session layer, but that didn't change what happened. I still got new sessions for every request

**Comment by maxcountryman** [comment]
Next try same site.

Getting a new session implies the client is not sending the cookie with the request.

That's likely because of the cookie settings. But you should also inspect the client to see what's happening there.

**Comment by maxcountryman** [comment]
You've identified the issue: your client is not sending the cookie.

To fix this you'll have to dig into what cookie settings are necessary to ensure the client sends the cookies.

For dev I would suggest disabling secure and using lax same site.

MDN has good documentation around these topics that might help.

**Comment by BeaconBrigade** [comment]
Alright thanks for your help!

**Comment by maxcountryman** [comment]
@ejmg please try what I suggested above. These issues relate to how clients (in this case Chrome) will transmit cookies. Cookies need to be configured such that the client will transmit them as expected. The underlying crate for managing sessions exposes an interface for configuring these.

**Comment by maxcountryman** [comment]
@ejmg curious in what way? You weren't expecting axum-login to the query the user store?

**Comment by maxcountryman** [comment]
@ejmg are you trying to access the the user value in the session directly? I think I'm confused about what you ran into here.

**Comment by maxcountryman** [comment]
@ejmg ah okay, thanks for the detailed explanation. I think I understand now. The confusion is that axum-login doesn't take an updated user and write it to the store. In other words it doesn't manage the state of the user store in a write fashion only in a read fashion. Is there something we could do in the docs or examples to make that more obvious?
