### ISSUE TITLE
Incorrect use of the `tower_http::auth::RequireAuthorizarionLayer`

### ISSUE THREAD

**Issue by czocher** [maxcountryman/axum-login#55]
Hello @maxcountryman,
While reading the documentation for the `RequireAuthorizarionLayer` I noticed this crate does not use it according to its assumed use-case. 
The documentation for it states that it's a:
```Middleware that authorizes all requests using the Authorization header. ```
Correct me if I'm wrong, but neither this crate, nor the underlying `axum_sessions` uses the standard [Authorization ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization)  header to keep track of the user, but uses cookie-stored sessions instead.
Since they introduced a breaking change in the 0.4.0 version, making the layer async, maybe it's a good time to migrate away from it?

**Comment by maxcountryman** [comment]
Sure, I'm happy to adopt another mechanism. I believe there's examples of them not using `Authorization` so it seemed reasonable to use it here too. But if its API is changing anyway then I'm fine to migrate away.

**Comment by Czocher** [comment]
I think they changed it in the new version, we should use: https://docs.rs/tower-http/latest/tower_http/auth/require_authorization/index.html
Instead.

**Comment by czocher** [comment]
Fixed by https://github.com/maxcountryman/axum-login/pull/65
