### ISSUE TITLE
`AuthUser` should not require the `Debug` trait

### ISSUE THREAD

**Issue by Czocher** [maxcountryman/axum-login#6]
Currently the `AuthUser` requires the `std::fmt::Debug` trait to be implemented. I believe it's a leftover from some debugging implementation and should not be required. In reality it can even be considered a security issue due to the fact it forces the structs implementing this trait to also implement `Debug` and possibly print the password hash to an insecure channel like the console, logs or API error response.

**Comment by maxcountryman** [comment]
I think we can remove it.
