### ISSUE TITLE
Trait `UserStore` depends on eyre

### ISSUE THREAD

**Issue by ondrowan** [maxcountryman/axum-login#60]
I've tried to implement custom `UserStore`, but the return type of method `load_user` depends on `eyre`'s `Report` which I'm not using in my application. It'd probably make more sense to give implementors more freedom and require `std::error::Error` instead.

**Comment by maxcountryman** [comment]
💯

Yes I agree. Sorry you've run into this. Let's change it.

**Comment by maxcountryman** [comment]
Closed by #69.

**Comment by ondrowan** [comment]
Thanks for the fix!

**Comment by emirror-de** [comment]
Is there a way to use the updated `UserStore` with `anyhow`? Using `anyhow::Error` on `axum_login = "0.6"` fails with:

```
error[E0277]: the trait bound `anyhow::Error: StdError` is not satisfied
   --> test/src/user.rs:128:18
    |
128 |     type Error = anyhow::Error;
    |                  ^^^^^^^^^^^^^ the trait `StdError` is not implemented for `anyhow::Error`
    |
note: required by a bound in `axum_login::UserStore::Error`
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-login-0.6.0/src/user_store.rs:16:17
    |
16  |     type Error: std::error::Error + Send;
    |                 ^^^^^^^^^^^^^^^^^ required by this bound in `UserStore::Error`
```
