### ISSUE TITLE
`AuthContext` usage panics in streaming handler

### ISSUE THREAD

**Issue by OvermindDL1** [maxcountryman/axum-login#63]
As demonstrated at:
https://github.com/OvermindDL1/issue_axum_session_streaming.git

I have a large'ish app using graphql and a liveview-like thing and wanted to toss in axum-login and axum-sessions for obvious usefulness, however attempting to use it in either of these things, which are streaming handlers, panics with:

```rs
thread 'tokio-runtime-worker' panicked at 'Session handle still has owners.: RwLock { mr: 536870911, s: Semaphore { permits: 536870911 }, c: UnsafeCell { .. } }'
```

I reduced the issue to the SSCCE in the above git repo to strip all external things and just keep to axum and future_utils.  Given this handler:
```rs
// Doesn't work, axum-login is blowing up
async fn route_streaming_login(mut auth: AuthContext) -> StreamBody<impl Stream<Item = std::io::Result<&'static str>>> {
	let stream = stream::once(async move {
		// performing some long operation
		tokio::time::sleep(std::time::Duration::from_secs(2)).await;
		// And need to access auth 'later' in the stream
		auth.login(&User { id: 1 }).await.unwrap();
		Ok("logged in")
	});
	StreamBody::new(stream)
}
```
When it hits the `auth.login(&User { id: 1 }).await.unwrap();` it panics, not because of the unwrap but internally (it never returns).

It looks like internally it's clearing, resetting, something the session from the handler, but that shouldn't be done because it's still being processed axum/hyper to finish processing and sending information mid-stream.

What should 'probably' be done is that `AuthContext` is a fully owned type that resets itself in the store internally when it is dropped (which yes it would likely need to hold an Arc to the store internally in that case unless some re-architecting is done first), rather than when the handler returns (which is *definitely* not when the work is complete in axum/hyper).  This will match what other things in the axum ecosystem do and will allow it to work within an axum streaming context like other things do as well.

**Comment by OvermindDL1** [comment]
As an aside, I also have this test route:
```rs
// And interestingly discovered axum-sessions causes a freeze when the session is interacted with
async fn route_session(mut session: WritableSession) -> StreamBody<impl Stream<Item = std::io::Result<&'static str>>> {
	let stream = stream::once(async move {
		// performing some long operation
		tokio::time::sleep(std::time::Duration::from_secs(2)).await;
		// And need to access session 'later' in the stream
		session.insert("test", 42).unwrap();
		Ok("got session")
	});
	StreamBody::new(stream)
}
```
Interaction with an axum-sessions from a streaming context just... locks  up, a lock is waited on but never released it seems.

No such issues with a plain async-session.

**Comment by maxcountryman** [comment]
We will be removing the lock as soon as upstream async-session lands the ability to clone without blowing away the session value.

I'm not exactly sure what's going on here, if we can find a fix I'm happy to release that until upstream async-session is updated.

**Comment by OvermindDL1** [comment]
I might be too busy this weekend to get to a computer but I can try Monday.

I'm pretty sure that adding a drop implementation on and moving a touch more data into the `AuthContext` (and moving basically all of the work that occurs after the inner call into that drop) along with a few other minor changes (maybe across both sessions and login libs) is the quickest way to fix it, and it might be backwards compatible if done in a certain way, should be a fairly small patch though from what I looked at.

**Comment by OvermindDL1** [comment]
From looking at things I'm not actually sure async_session's Session type needs to be cloneable, in fact it probably shouldn't be...

**Comment by maxcountryman** [comment]
If I recall, there's issues with Send that require Clone, but it's been a while since I've looked at it.

If we come up with better ways of approaching this I will be more than happy to incorporate those. 😁

**Comment by benwis** [comment]
Leaving a note here so I can track progress. Unfortunately the inability to work with streaming prevents me from using it, so I'm rooting for either of you or async_session to find a solution.

**Comment by OvermindDL1** [comment]
For note, working on this in #61, same issue I'm guessing, or I put notes on the wrong things

**Comment by maxcountryman** [comment]
This is address in `v0.7.0` which now uses `tower-sessions`.
