### ISSUE TITLE
Idea: `AuthUser` should not be `Clone` and should require the `Zeroize` trait on the `password` field

### ISSUE THREAD

**Issue by Czocher** [maxcountryman/axum-login#7]
Currently `AuthUser` requires the `Clone` trait to be implemented on the `User` struct. This is not bad per-say but is not good in terms of secret management hygiene.

I suggest the `AuthUser` should handle the password hash very carefully and require the password field to be [`Zeroizable`](https://crates.io/crates/zeroize), so that the password is not cloned nor left in memory. Returning a `&str` instead would possibly also be beneficial rather than `String`.

This is possibly a breaking change.

Idea: `AuthUser` can return a [`SecretString`](https://docs.rs/secrecy/0.8.0/secrecy/type.SecretString.html) of the password.

**Comment by maxcountryman** [comment]
I'm very much open to changing this, even if it results in a breaking change.
