### ISSUE TITLE
Proposal to Implement NoSQL Stores such as MongoDB and Redis

### ISSUE THREAD

**Issue by davidbayo10** [maxcountryman/axum-login#76]
I trust this message finds you well. I wanted to share an idea that I believe could significantly enrich our product.

At present, axum-login relies on SQL database systems to store and manage user information. While these systems are powerful and have been useful so far, I propose that we also include support for NoSQL databases, specifically MongoDB and Redis. Incorporating these could provide significant benefits in terms of scalability, performance, and flexibility.

NoSQL databases are known for their high scalability and flexibility, allowing for a more efficient handling of large data sets and complex data structures. MongoDB, for example, uses a document-oriented model that can store vast amounts of data in varied formats, and its distributed architecture ensures high availability and scalability. On the other hand, Redis, an in-memory data structure store, can serve as a database, cache, and message broker, providing exceptional performance for real-time applications.

By supporting NoSQL databases, we can make our system more versatile, catering to a wider range of use cases and potential clients. This could also make our system more robust and future-proof, as NoSQL databases are increasingly being adopted in the industry.

I look forward to hearing your thoughts on this matter.

**Comment by davidbayo10** [comment]
Thank you for your positive response and for being open to the suggestion of incorporating NoSQL support into axum-login. I understand that thanks to axum-sessions and async-session, we can leverage any store for which we have implemented the necessary traits, which is great to hear.

I'm writing to seek clarification on a few points. Firstly, who will be responsible for this development? Will this task be assigned internally within the team?

I look forward to your response.

**Comment by maxcountryman** [comment]
This is an open source project with no team behind it, per se. If you'd like to take this on, we'd be happy to look at a PR.

**Comment by davidbayo10** [comment]
Thank you for your quick response. I greatly appreciate your willingness to consider my contributions.

With that in mind, I would like to take on the responsibility of implementing the NoSQL support feature. My aim is to start working on this as soon as possible and to submit a pull request once I'm confident with the robustness and efficiency of the implementation.

Please be informed that I have been programming in Rust for only a year and a half. Despite my relatively short experience with Rust, I am committed to providing a quality contribution that meets the high standards of this project. I understand the weight of this responsibility and will make sure to proceed with careful testing and adherence to best practices.

**Comment by maxcountryman** [comment]
With the release of `v0.7.0` we no longer bundle session stores/backends.
