### ISSUE TITLE
Cross-origin WebSocket requests are rejected with 401

### ISSUE THREAD

**Issue by bclarke123** [maxcountryman/axum-login#79]
Hi, thanks for all your efforts making axum-login, it's extremely useful!

I have found an issue when creating an API using CORS, where any attempt to put a WebSocket endpoint behind `RequireAuthorizationLayer::login()` causes it to unconditionally return `401 Unauthorized`, whether or not the user is logged in.  I have traced this issue back as far as I'm able, in [authorize()](https://github.com/maxcountryman/axum-login/blob/main/axum-login/src/auth.rs#L222) the user is None.  Changing CORS or Cookie settings do not appear to have any effect.

Steps to Reproduce:

- Clone and run https://github.com/bclarke123/auth-ws-mre
- Navigate browser to http://localhost:3001/ and open the developer console - this will make a login request to port 3000 (making it cross origin), the login request should succeed, then the websocket request should fail.  Enabling tracing on the server will show it quietly returning a 401.
- Close the browser window, open a new one, and navigate to http://localhost:3000/ - you should observe in the console that the websocket connection succeeds, as the request is no longer cross-origin.
- Interestingly, in Chrome, if you now change the URL in the address bar _back_ to port 3001, the cross-origin websocket connection seems to begin working, after making a request from the same origin.  I'm not sure if this is a quirk of connection pooling in Chrome or something, but if the steps are not followed in this order it's possible to miss the issue.

Thanks again, if I can do anything to help track this down I'm happy to help!

**Comment by maxcountryman** [comment]
What happens if you use a static secret instead of one that's generated at runtime?

**Comment by maxcountryman** [comment]
Are you trying to share the cookie between two domains? I don't think that's intended to work, depending on how you have `axum-sessions` configured.

**Comment by bclarke123** [comment]
Thanks for the thought, the cookie is http-only and only used for one
origin (port 3000 in the case of my linked example). Everything works as
expected, except initiating a WebSocket request from a front end on port
3001, to an API on port 3000 (again, as an example - the only difference is
whether the request is cross-origin or not).

Thanks, hope that clarifies!

**Comment by maxcountryman** [comment]
I wouldn't expect that to work for the exact reason you state: it's cross-origin.

**Comment by bclarke123** [comment]
It's configured to use CORS, and there's mountains of precedent on the Internet for using WebSockets across origins - perhaps if it's not supported, as an outlier in the API where any other request is fine with it, could it give a more helpful error than nothing?

**Comment by maxcountryman** [comment]
If there's an issue with CORS, what would point to that being an issue with this crate?

It's difficult to help without there being a concrete issue that we can demonstrate in this crate, as opposed to some other crate, or the application code.

I would start by narrowing down the issue such that we can definitively point to where your problem is occurring.

**Comment by bclarke123** [comment]
Thanks - the only crate in this stack which responds with a 401 in any case at all, as far as I can tell, is this crate.  I worked with a few people in the #axum channel on the tokio discord who agreed it was an issue with this crate.  The MRE I have should (I hope) be a sufficiently narrow example of the problem to track it down, as I've said a few times I'm happy to help track it down further, as I'm able - is there some revision to the MRE you would like to see to narrow it down further?

**Comment by maxcountryman** [comment]
It's not enough to say "it's an issue with this crate". What is the issue exactly? If that can't be answered then that's where you should begin.

> The MRE I have should (I hope) be a sufficiently narrow example of the problem to track it down

It sounds like you're on the right track, so please do let us know what you uncover.

While I can't conduct the investigation for you, from what you've shared my strong hunch is there's a problem with how your cookies are being constructed (namely that they need to be shared between domains).
