### ISSUE TITLE
Idea: Add an example for a simple `is_admin` extractor

### ISSUE THREAD

**Issue by Czocher** [maxcountryman/axum-login#8]
A new example in the `examples` directory, which would show how to require not only a logged in user, but a user with a given "permission" (like a field `is_admin` set to `true`) would be very helpful for beginners.

Maybe creating a generic extractor trait to check some permission (which later can be specified to a `RequireAdmin` extractor or some other permission) by the end-user would also be helpful.

**Comment by maxcountryman** [comment]
Love this idea.

There's also room to eventually include more sophisticated access controls (e.g. RBAC). I haven't explored this direction at all, however I like starting with your idea.

**Comment by Czocher** [comment]
Thanks, I really love your work @maxcountryman! I'm a rust-beginner, but if you feel like I can help somehow feel free to mark tasks as "good-first-issue" or something and I'll gladly provide a PR.
