### ISSUE TITLE
Issues with PgPool type

### ISSUE THREAD

**Issue by sixilli** [maxcountryman/axum-login#84]
Running this code I get a type error on the last line. The issue seems to be that axum-login is using `sqlx_core's` implementation of PgPool.

```rust
use sqlx::{Pool, Postgres, PgPool};

pub async fn new_app() -> Option<Router> {
    let pool = PgPoolOptions::new()
        .max_connections(5)
        .connect("postgres://moose:test@localhost/test")
        .await
        .unwrap();
        
    let pg_pool: PgPool = pool.clone();

    let mut secret = [0u8; 64];
    thread_rng().fill(&mut secret);

    let session_store = UserSessionStore::new(&pool);
    let session_layer = SessionLayer::new(session_store, &secret);

    let user_store = PostgresStore::<User, Role>::new(pg_pool);
```

```
mismatched types [E0308] expected `sqlx_core::postgres::PgPool`, found `PgPool` 
```

**Comment by czocher** [comment]
Yes, currently `axum-login` is thightly coupled with `sqlx`, we're on our way to decouple it (see #78). You'll need to use the `sqlx` `PgPool` for now unfortunately. See: https://github.com/launchbadge/sqlx/blob/main/examples/postgres/todos/src/main.rs#L20 for a use-example of `PgPool` in `sqlx`.

**Comment by sixilli** [comment]
Sweet ty for the quick response I'll try that out and see how it goes. It seems like an odd idea to use `slx_core's` versions of `PgPool`. But I'm glad it's being looked into. In terms of making a clean API I think it might be a good idea to let end users implement their own traits for `UserStrore`. I implemented my own when this wasn't working and it's a pretty painless experience since I could follow the macro. If it was covered in documentation it would have saved me a lot of effort.  I'm not sure if my own store works yet, but I'll give both a try.

**Comment by czocher** [comment]
Thanks for your suggestion @sixilli I'll add it to the TODO for #78.

**Comment by DnOberon** [comment]
@sixilli  how did you fix this?
