### ISSUE TITLE
Create an example for password and token based auth at the same time

### ISSUE THREAD

**Issue by czocher** [maxcountryman/axum-login#86]
As suggested in https://github.com/maxcountryman/axum-login/discussions/85 it would be a nice idea to have an example for situations where one would like to authenticate a user with two different secrets - a token a and a password.

**Comment by maxcountryman** [comment]
We now have [one example](https://github.com/maxcountryman/axum-login/tree/main/examples/multi-auth) of using both a password or OAuth.
