### ISSUE TITLE
examples/sqlite database in wrong folder and useless files

### ISSUE THREAD

**Issue by mobergmann** [maxcountryman/axum-login#98]
- According to the [`examples/sqlite/src/main.rs`](https://github.com/maxcountryman/axum-login/blob/bb7e5d32100bb6846412cee1f26851cc47397991/examples/sqlite/src/main.rs#L43) file the database should be in the path `sqlite/user_store.db`, but it actually is in the examples root folder.
- We also don't need the `user_store.db-shm` and `user_store.db-wal` files, [as these are temporary files](https://stackoverflow.com/a/7779752/11186407).

I propose fixing this issue by moving the `user_store.db`file into a `sqlite` folder and removing the `user_store.db-shm` and `user_store.db-wal` files.  
I already made these changes [on a fork](https://github.com/maxcountryman/axum-login/compare/main...mobergmann:axum-login:fix/example-sqlite-database-path). I you allow I will create a Pull Request.

**Comment by maxcountryman** [comment]
Thanks for this--those files were not included intentionally. I'd be happy to merge your patch.

**Comment by maxcountryman** [comment]
Merged via #99.
